exports.seed = (knex, Promise) => {
  return knex('skills').del()
  .then(() => {
    return Promise.join(
      knex('skills').insert({
        id: 1,
        jackOfAllTrades: false,
        acrobaticsProf: false,
        acrobaticsExp: false,
        animalhandlingProf: false,
        animalhandlingExp: false,
        arcanaProf: true,
        arcanaExp: false,
        athleticsProf: true,
        athleticsExp: false,
        deceptionProf: false,
        deceptionExp: false,
        historyProf: false,
        historyExp: false,
        insightProf: false,
        insightExp: false,
        intimidationProf: false,
        intimidationExp: false,
        investigationProf: true,
        investigationExp: false,
        medicineProf: true,
        medicineExp: false,
        natureProf: false,
        natureExp: false,
        perceptionProf: false,
        perceptionExp: false,
        performanceProf: false,
        performanceExp: false,
        persuasionProf: false,
        persuasionExp: false,
        religionProf: false,
        religionExp: false,
        sleightofhandProf: true,
        sleightofhandExp: false,
        stealthProf: false,
        stealthExp: false,
        survivalProf: false,
        survivalExp: false,
        custom1Prof: false,
        custom1Exp: false,
        custom1Name: 'Stonecunning',
        custom1Stat: 'int',
        custom2Prof: true,
        custom2Exp: true,
        custom2Name: 'Custom 2',
        custom2Stat: 'str',
        custom3Prof: false,
        custom3Exp: false,
        custom3Name: 'Custom 3',
        custom3Stat: 'str',
        custom4Prof: false,
        custom4Exp: false,
        custom4Name: 'Custom 4',
        custom4Stat: 'str',
        custom5Prof: false,
        custom5Exp: false,
        custom5Name: 'Custom 5',
        custom5Stat: 'str'
      })
    );
  });
};
